//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppEnitity.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppVersion
    {
        public int AppID { get; set; }
        public string AppName { get; set; }
        public string AppDescription { get; set; }
        public string AppRute { get; set; }
        public string AppLastEditBy { get; set; }
        public Nullable<System.DateTime> AppLastEditDt { get; set; }
    }
}
